# Header
menu:
  過去の投稿: /archives
rss: http://cloud.feedly.com/#subscription%2Ffeed%2Fhttps%3A%2F%2Flaysakura.github.io%2Fatom.xml

# Content
excerpt_link: 続きを読む
fancybox: true
toc:
  maxdepth: 4

# Miscellaneous
google_analytics: UA-22289437-2
favicon: /favicon.png
